import { z28 } from "./j3/m3";
import { HashMap } from '@kit.ArkTS';
import { d27 } from "./q3";
import { LoggerAdapter } from "../c/d/LoggerAdapter";
export declare class b24 {
    private static readonly e16;
    private static logDir;
    private static cacheDir;
    private static pubKey;
    private static consoleLog;
    private static maxFileSize;
    private static maxAliveTime;
    private static subLogDirs;
    private static m16;
    private static j16;
    private static j12?;
    static t15(w27: Array<string> | null): void;
    static g16(): Array<string> | null;
    static v15(): LoggerAdapter;
    static h16(): HashMap<string, d27>;
    static k16(): boolean;
    static s15(dir: string): void;
    static f16(): string;
    static l16(dir: string): void;
    static getCacheDir(): string;
    static r15(key: string): void;
    static getPubKey(): string;
    static q15(v27: z28): void;
    static n15(): z28;
    static setMaxFileSize(u27: number): void;
    static setMaxAliveTime(t27: number): void;
    static appenderOpen(level: number, mode: number, s27: string, namePrefix: string): void;
    static appenderClose(): void;
    static appenderFlush(): void;
    static n16(isSync: boolean): void;
    static getLogLevel(): number;
    static setLogLevel(level: number): void;
    static setConsoleLogOpen(p27: boolean): void;
    static f(tag: string, message: string): void;
    static e(tag: string, message: string): void;
    static w(tag: string, message: string): void;
    static i(tag: string, message: string): void;
    static d(tag: string, message: string): void;
    static v(tag: string, message: string): void;
    static printErrStackTrace(tag: string, error: Error, message: string): void;
    static w15(level: number, mode: number, f27: string, namePrefix: string): d27;
    static x15(prefix: string): void;
    static y15(prefix: string): d27;
}
