export declare function h14(url: string, body: string, appId: string, j22: string, k22: number): boolean;
export declare function i14(url: string, path: string, fileName: string, g22: Array<string>, h22: Array<string>, i22: number): boolean;
export declare function j14(e22: Array<string>): Array<string>;
export declare function k14(b22: Array<string>, c22: Array<string>): void;
export declare function o14(a22: Array<string>): void;
export declare function p14(text: string, key: string): string;
export declare function zipFile(fileList: Array<string>, w21: string, x21: number): void;
export declare function q14(data: ArrayBuffer, len: number): string;
export declare function setLogLevel(level: number, endTime: number): void;
export declare function r14(): void;
export declare function s14(isSuccess: boolean): void;
